# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Print one object grasp pose generated by NVlabs/GraspGenX.

This is an offline helper. Run it with a GraspGenX Python environment, inspect
the printed offset/quaternion, and manually copy the values into a task config
if needed.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np

MOE_Z_OFFSETS_CM = tuple(range(-16, 4))


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--graspgenx_root",
        type=Path,
        required=True,
        help="Path to an NVlabs/GraspGenX checkout.",
    )
    parser.add_argument(
        "--assets_dir",
        type=Path,
        default=None,
        help="GraspGenX assets directory. Defaults to <graspgenx_root>/assets.",
    )
    parser.add_argument(
        "--checkpoints",
        type=Path,
        default=None,
        help="Optional GraspGenX checkpoint root containing gen/ and dis/ directories.",
    )
    parser.add_argument("--gripper_name", type=str, required=True, help="GraspGenX gripper descriptor name.")
    parser.add_argument(
        "--target_gripper_name",
        type=str,
        default=None,
        help="Optional real gripper name when using a GraspGenX descriptor as a surrogate.",
    )
    parser.add_argument("--object_mesh", type=Path, required=True, help="Object USD or mesh file.")
    parser.add_argument(
        "--config_key",
        type=str,
        default="object",
        help="Name printed in the copy-paste config entry, e.g. gear_small.",
    )
    parser.add_argument("--num_sample_points", type=int, default=5000, help="Surface points sampled from the object.")
    parser.add_argument("--num_grasps", type=int, default=1200, help="Diffusion grasps to sample.")
    parser.add_argument("--seed", type=int, default=23, help="Random seed for mesh sampling and GraspGenX.")
    parser.add_argument(
        "--target_offset_xyz",
        type=float,
        nargs=3,
        default=None,
        metavar=("X", "Y", "Z"),
        help="Optional expected object-to-EE offset [m] used to select a candidate near an existing task grasp.",
    )
    parser.add_argument(
        "--target_quat_xyzw",
        type=float,
        nargs=4,
        default=None,
        metavar=("X", "Y", "Z", "W"),
        help="Optional expected object-to-EE rotation used with --target_offset_xyz.",
    )
    parser.add_argument(
        "--ee_from_grasp_pos",
        type=float,
        nargs=3,
        default=(0.0, 0.0, 0.0),
        metavar=("X", "Y", "Z"),
        help="Translation from the GraspGenX gripper frame to the task EE frame [m].",
    )
    parser.add_argument(
        "--ee_from_grasp_quat_xyzw",
        type=float,
        nargs=4,
        default=(0.0, 0.0, 0.0, 1.0),
        metavar=("X", "Y", "Z", "W"),
        help="Rotation from the GraspGenX gripper frame to the task EE frame.",
    )
    args = parser.parse_args()
    if (args.target_offset_xyz is None) != (args.target_quat_xyzw is None):
        parser.error("--target_offset_xyz and --target_quat_xyzw must be provided together.")
    return args


def _prepare_graspgenx_imports(graspgenx_root: Path):
    """Import GraspGenX modules after adding the checkout to ``sys.path``."""
    sys.path.insert(0, str(graspgenx_root.expanduser().resolve()))
    try:
        import torch
        import trimesh
        import trimesh.transformations as tra
        from graspgenx import get_checkpoints_version_dir
        from graspgenx.grasp_server import GraspGenXSampler
        from graspgenx.samplers import run_planner_on_object
        from graspgenx.utils.checkpoint_io import load_model_cfg
    except ImportError as exc:
        raise ImportError(
            "Run this script with the GraspGenX environment, for example "
            "`/tmp/GraspGenX/.venv/bin/python scripts/tools/generate_grasp_pose_values_graspgenx.py ...`."
        ) from exc

    return torch, trimesh, tra, get_checkpoints_version_dir, GraspGenXSampler, load_model_cfg, run_planner_on_object


def _load_mesh_points(mesh_file: Path, num_sample_points: int, trimesh: Any, tra: Any):
    """Load object mesh points centered for GraspGenX and return the restore transform."""
    mesh_file = mesh_file.expanduser().resolve()
    if mesh_file.suffix.lower() in (".usd", ".usda", ".usdc", ".usdz"):
        import scene_synthesizer as synth

        mesh = synth.Asset(str(mesh_file)).mesh()
    else:
        mesh = trimesh.load(str(mesh_file))

    xyz, _ = trimesh.sample.sample_surface(mesh, num_sample_points)
    xyz = np.asarray(xyz, dtype=np.float32)

    transform_subtract_mean = tra.translation_matrix(-xyz.mean(axis=0))
    centered_xyz = tra.transform_points(xyz, transform_subtract_mean)
    return centered_xyz, tra.inverse_matrix(transform_subtract_mean)


def _matrix_from_pos_quat_xyzw(
    pos: tuple[float, ...] | list[float],
    quat_xyzw: tuple[float, ...] | list[float],
    tra: Any,
):
    quat = np.asarray(quat_xyzw, dtype=np.float64)
    quat = quat / np.linalg.norm(quat)
    transform = tra.quaternion_matrix([quat[3], quat[0], quat[1], quat[2]])
    transform[:3, 3] = np.asarray(pos, dtype=np.float64)
    return transform


def _quat_xyzw_from_matrix(transform: np.ndarray, tra: Any) -> np.ndarray:
    quat_wxyz = np.asarray(tra.quaternion_from_matrix(transform), dtype=np.float64)
    quat_wxyz = quat_wxyz / np.linalg.norm(quat_wxyz)
    if quat_wxyz[0] < 0.0:
        quat_wxyz = -quat_wxyz
    return np.asarray([quat_wxyz[1], quat_wxyz[2], quat_wxyz[3], quat_wxyz[0]], dtype=np.float64)


def _quat_angle_rad(quat_1: np.ndarray, quat_2: np.ndarray) -> float:
    quat_1 = quat_1 / np.linalg.norm(quat_1)
    quat_2 = quat_2 / np.linalg.norm(quat_2)
    dot = abs(float(np.dot(quat_1, quat_2)))
    return float(2.0 * np.arccos(np.clip(dot, -1.0, 1.0)))


def _round_list(values: np.ndarray, digits: int = 9) -> list[float]:
    return [round(float(value), digits) for value in values]


def _pose_to_config_values(transform_object_ee: np.ndarray, tra: Any) -> tuple[list[float], list[float]]:
    """Convert an object-frame EE pose into config offset and quaternion values."""
    rotation_object_ee = transform_object_ee[:3, :3]
    position_object_ee = transform_object_ee[:3, 3]
    offset_in_ee_frame = rotation_object_ee.T @ position_object_ee
    return _round_list(offset_in_ee_frame), _round_list(_quat_xyzw_from_matrix(transform_object_ee, tra))


def _select_candidate(
    candidate_poses: np.ndarray,
    confidence: np.ndarray,
    branch_tags: list[str],
    args: argparse.Namespace,
    tra: Any,
) -> tuple[int, dict[str, float | int | str]]:
    """Select top confidence or the candidate closest to a provided target pose."""
    if args.target_offset_xyz is None:
        best_index = int(confidence.argmax())
        return best_index, {
            "selection": "top_confidence",
            "branch": branch_tags[best_index],
            "confidence": round(float(confidence[best_index]), 6),
            "candidate_index": best_index,
        }

    target_offset = np.asarray(args.target_offset_xyz, dtype=np.float64)
    target_quat = np.asarray(args.target_quat_xyzw, dtype=np.float64)
    target_quat = target_quat / np.linalg.norm(target_quat)

    best_index = 0
    best_score = float("inf")
    best_meta: dict[str, float | int | str] = {}
    for index, transform in enumerate(candidate_poses):
        offset, quat_xyzw = _pose_to_config_values(transform, tra)
        offset_array = np.asarray(offset, dtype=np.float64)
        quat_array = np.asarray(quat_xyzw, dtype=np.float64)
        xyz_error = float(np.linalg.norm(offset_array - target_offset))
        rotation_error = _quat_angle_rad(quat_array, target_quat)
        score = 45.0 * xyz_error + 3.0 * rotation_error - 0.005 * float(confidence[index])
        if score < best_score:
            best_index = index
            best_score = score
            best_meta = {
                "selection": "target_pose",
                "branch": branch_tags[index],
                "confidence": round(float(confidence[index]), 6),
                "xyz_error_m": round(xyz_error, 9),
                "rotation_error_deg": round(float(np.rad2deg(rotation_error)), 6),
                "candidate_index": int(index),
            }

    return best_index, best_meta


def _run_graspgenx(args: argparse.Namespace, modules: tuple[Any, ...], grasp_sampler: Any):
    _torch, trimesh, tra, _checkpoints, _GraspGenXSampler, _load_cfg, run_planner_on_object = modules
    points, restore_transform = _load_mesh_points(args.object_mesh, args.num_sample_points, trimesh, tra)
    grasps, confidence, branch_tags, _obb = run_planner_on_object(
        points,
        grasp_sampler,
        planner="graspmoe",
        grasp_threshold=-1.0,
        num_grasps=args.num_grasps,
        topk_num_grasps=-1,
        moe_num_yaws=144,
        moe_z_offsets_cm=MOE_Z_OFFSETS_CM,
        moe_outlier_threshold=0.014,
        moe_outlier_k=20,
        moe_obb_mode="advanced",
        moe_skip_obb_rule="never",
        moe_obb_density="dense-topandside",
        moe_obb_position_spacing_cm=0.25,
    )
    if len(grasps) == 0:
        raise RuntimeError(f"GraspGenX did not return any grasps for {args.object_mesh}.")

    grasps = grasps.detach().cpu().numpy() if hasattr(grasps, "detach") else np.asarray(grasps)
    confidence = confidence.detach().cpu().numpy() if hasattr(confidence, "detach") else np.asarray(confidence)
    grasps[:, 3, 3] = 1.0

    grasp_to_ee = _matrix_from_pos_quat_xyzw(args.ee_from_grasp_pos, args.ee_from_grasp_quat_xyzw, tra)
    candidate_poses = np.asarray([restore_transform @ grasp @ grasp_to_ee for grasp in grasps], dtype=np.float64)
    best_index, meta = _select_candidate(candidate_poses, confidence, branch_tags, args, tra)
    offset, quat_xyzw = _pose_to_config_values(candidate_poses[best_index], tra)

    if args.target_quat_xyzw is not None:
        target_quat = np.asarray(args.target_quat_xyzw, dtype=np.float64)
        target_quat = target_quat / np.linalg.norm(target_quat)
        quat = np.asarray(quat_xyzw, dtype=np.float64)
        if float(np.dot(quat, target_quat)) < 0.0:
            quat_xyzw = _round_list(-quat)

    meta["num_candidates"] = int(len(grasps))
    return offset, quat_xyzw, meta


def main() -> None:
    """Run GraspGenX and print manual config values."""
    args = parse_args()
    modules = _prepare_graspgenx_imports(args.graspgenx_root)
    torch, _trimesh, _tra, get_checkpoints_version_dir, GraspGenXSampler, load_model_cfg, _planner = modules

    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)

    checkpoint_root = args.checkpoints or Path(get_checkpoints_version_dir())
    model_cfg = load_model_cfg(os.path.join(checkpoint_root, "gen"), os.path.join(checkpoint_root, "dis"), None, None)
    assets_dir = args.assets_dir or args.graspgenx_root.expanduser().resolve() / "assets"
    grasp_sampler = GraspGenXSampler(model_cfg, args.gripper_name, assets_dir=str(assets_dir.expanduser().resolve()))

    print(f"Running GraspGenX for object: {args.object_mesh}", file=sys.stderr)
    offset, quat_xyzw, meta = _run_graspgenx(args, modules, grasp_sampler)

    gripper_label = args.target_gripper_name or args.gripper_name
    print(f"\n# Suggested grasp values for {args.config_key} with {gripper_label}.")
    print("# Offset is object-to-EE translation in the rotated EE frame [m].")
    print(f'gear_offsets_grasp entry: "{args.config_key}": {offset},')
    print(f"grasp_rot_offset = {quat_xyzw}")
    print(f"selection = {meta}")


if __name__ == "__main__":
    main()
